# Generated by Django 6.0.7 on 2026-10-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0016_meeting_is_extended_meeting_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagInstructorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_questions', models.BooleanField(default=True)),
                ('allow_summaries', models.BooleanField(default=True)),
                ('allow_quiz', models.BooleanField(default=True)),
                ('allow_revision', models.BooleanField(default=True)),
                ('show_citations', models.BooleanField(default=True)),
                ('allow_change_scope', models.BooleanField(default=True)),
                ('allow_outside_knowledge', models.BooleanField(default=False)),
                ('strict_material_mode', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_setting', to='meetings.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='RagSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI Study Session', max_length=255)),
                ('strict_mode', models.BooleanField(default=True)),
                ('active_mode', models.CharField(default='ask', max_length=50)),
                ('explain_level', models.CharField(default='detailed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_sessions', to='meetings.classroom')),
                ('selected_materials', models.ManyToManyField(blank=True, related_name='rag_sessions', to='meetings.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Study Session',
                'verbose_name_plural': 'RAG Study Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RagQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='ask', max_length=30)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('retrieved_chunks_count', models.IntegerField(default=0)),
                ('sources_cited', models.JSONField(blank=True, default=list)),
                ('strict_mode_applied', models.BooleanField(default=True)),
                ('not_found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_query_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='rag_workspace.ragsession')),
            ],
            options={
                'verbose_name': 'RAG Query Log',
                'verbose_name_plural': 'RAG Query Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
