# Generated by Django 6.0.7 on 2026-10-05 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag_workspace.ragsession')),
            ],
            options={
                'verbose_name': 'RAG Chat Message',
                'verbose_name_plural': 'RAG Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
