# Generated by Django 4.2.9 on 2026-07-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_is_chunked_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
