# Generated by Django 6.0.7 on 2026-08-15 02:52

import common.validators
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_likes_count_video_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_file',
            field=models.FileField(upload_to=videos.models.video_upload_path, validators=[common.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', validators=[common.validators.validate_image_file]),
        ),
    ]
