# Generated by Django 6.0.7 on 2026-10-04 11:49

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_original_file_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_master_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='bitrate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='codec',
            field=models.CharField(default='h265', max_length=20),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=videos.models.video_quality_upload_path),
        ),
    ]
