# Generated by Django 4.2.9 on 2026-09-30 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=30)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click Interaction'), ('form_submit', 'Form Submission'), ('media_event', 'Media Interaction'), ('http_request', 'HTTP API Request'), ('auth', 'Authentication Event'), ('custom', 'Custom Event')], db_index=True, max_length=50)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('page_url', models.TextField(blank=True)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('target_element', models.CharField(blank=True, max_length=255)),
                ('target_text', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='common_user_event_t_4045fb_idx'), models.Index(fields=['username', 'created_at'], name='common_user_usernam_976a21_idx'), models.Index(fields=['ip_address', 'created_at'], name='common_user_ip_addr_bd33e2_idx')],
            },
        ),
    ]
