# Generated by Django 4.2.9 on 2026-02-22 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camera_type', models.CharField(choices=[('ip_webcam', 'IP Webcam (Android)'), ('droidcam', 'DroidCam (iPhone)'), ('other', 'Other Mobile Camera')], default='ip_webcam', max_length=20)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.IntegerField(default=8080)),
                ('username', models.CharField(blank=True, help_text='Optional authentication username', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Optional authentication password', max_length=100)),
                ('stream_path', models.CharField(default='/video', help_text='e.g., /video for IP Webcam, /mjpegfeed for DroidCam', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileCameraPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_mobile_permissions', to=settings.AUTH_USER_MODEL)),
                ('mobile_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_cameras.mobilecamera')),
                ('teacher', models.ForeignKey(limit_choices_to={'userprofile__user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Camera Permission',
                'verbose_name_plural': 'Mobile Camera Permissions',
                'unique_together': {('mobile_camera', 'teacher')},
            },
        ),
    ]
