# Generated by Django 4.2.9 on 2026-03-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_started', 'Meeting Started'), ('meeting_cancelled', 'Meeting Cancelled'), ('classroom_joined', 'Classroom Join Request'), ('classroom_approved', 'Classroom Request Approved'), ('classroom_denied', 'Classroom Request Denied'), ('classroom_removed', 'Removed from Classroom'), ('student_joined', 'Student Joined Classroom'), ('meeting_reminder', 'Meeting Reminder'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_meeting_id', models.IntegerField(blank=True, null=True)),
                ('related_classroom_id', models.IntegerField(blank=True, null=True)),
                ('related_message_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='accounts_no_recipie_799191_idx'), models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx')],
            },
        ),
    ]
