# Generated by Django 4.2.9 on 2026-06-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_branch_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_friday',
            field=models.CharField(blank=True, default='10:00 – 14:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability_weekday',
            field=models.CharField(blank=True, default='09:00 – 17:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
