# Generated by Django 6.0.7 on 2026-08-15 08:16

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of email verification', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether user has verified their email address.'),
        ),
        migrations.RunPython(mark_existing_users_verified, reverse_code=migrations.RunPython.noop),
    ]
