# Generated by Django 4.2.9 on 2026-08-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_alter_meeting_student_can_view_camera_and_more'),
        ('accounts', '0015_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='meetings.classroom'),
        ),
    ]
