# Generated by Django 6.0.7 on 2026-08-27 09:56

import common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_conversation_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=common.encryption.EncryptedTextField(blank=True),
        ),
    ]
