# Generated by Django 4.2.9 on 2026-03-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_classroom_meeting_ended_at_meeting_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='total_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MeetingAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('join', 'Joined'), ('leave', 'Left')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='meetings.meetingparticipant')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
