# Generated by Django 4.2.9 on 2026-03-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meetingattendancelog_options_meetingsummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('removed', 'Removed'), ('left', 'Left')], default='pending', max_length=20),
        ),
    ]
