# Generated by Django 4.2.9 on 2026-03-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_add_left_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sleep_status',
            field=models.CharField(choices=[('active', 'Active'), ('sleeping', 'Sleeping')], default='active', max_length=20),
        ),
    ]
