# Generated by Django 4.2.9 on 2026-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_sleep_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='sleep_status',
            field=models.CharField(choices=[('active', 'Active'), ('sleeping', 'Sleeping')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
