# Generated by Django 4.2.9 on 2026-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_sleep_status_alter_meeting_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'live'])), fields=('classroom', 'title'), name='unique_active_meeting_title_per_classroom'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', True), ('status__in', ['scheduled', 'live'])), fields=('teacher', 'title'), name='unique_active_standalone_meeting_title_per_teacher'),
        ),
    ]
