# Generated by Django 4.2.9 on 2026-04-30 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0008_unique_active_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='global_camera_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='global_mute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='global_screenshare_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='audio_permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='screenshare_permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='video_permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='KickedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicked_at', models.DateTimeField(auto_now_add=True)),
                ('banned_until', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kicked_users', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
