# Generated by Django 4.2.9 on 2026-05-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_meeting_global_camera_off_meeting_global_mute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('classroom', 'Classroom'), ('temporary', 'Temporary')], default='temporary', max_length=20),
        ),
    ]
