# Generated by Django 4.2.9 on 2026-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='student_can_view_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='student_can_view_screenshare',
            field=models.BooleanField(default=False),
        ),
    ]
