# Generated by Django 4.2.9 on 2026-07-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_meeting_student_can_view_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='student_can_view_camera',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='student_can_view_screenshare',
            field=models.BooleanField(default=True),
        ),
    ]
