# Generated by Django 4.2.9 on 2026-08-16 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0012_alter_meeting_student_can_view_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_units', to='meetings.classroom')),
            ],
            options={
                'verbose_name': 'Material Unit',
                'verbose_name_plural': 'Material Units',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('document', 'Document / PDF / Word'), ('slides', 'Presentation / Slides'), ('notes', 'Lecture Notes / Markdown'), ('video', 'Video / Lecture Recording'), ('link', 'External Web Link / Resource'), ('book', 'e-Book / Reference Book')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=meetings.models.study_material_upload_path)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content_text', models.TextField(blank=True, help_text='Rich text / markdown notes content')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, help_text='Parsed plaintext for LLM/RAG search indexing')),
                ('summary_ai', models.TextField(blank=True, help_text='AI-generated conceptual summary')),
                ('key_topics', models.JSONField(blank=True, default=list, help_text='Extracted keywords/topics for hybrid search')),
                ('rag_indexed', models.BooleanField(db_index=True, default=False, help_text='True if document chunks are embedded in vector store')),
                ('rag_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('rag_metadata', models.JSONField(blank=True, default=dict, help_text='Vector IDs, model version & chunking metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='meetings.classroom')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='meetings.materialunit')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('embedding_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='meetings.studymaterial')),
            ],
            options={
                'verbose_name': 'Material Chunk',
                'verbose_name_plural': 'Material Chunks',
                'ordering': ['material', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='meetings.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('material', 'user')},
            },
        ),
    ]
