# Generated by Django 6.0.7 on 2026-08-27 09:56

import common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_materialunit_studymaterial_materialchunk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingchat',
            name='message',
            field=common.encryption.EncryptedTextField(),
        ),
    ]
