# Generated by Django 4.2.9 on 2026-08-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_alter_meetingchat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='auto_approve',
            field=models.BooleanField(default=False, help_text='Automatically approve students who join with valid class code & password'),
        ),
    ]
