# Generated by Django 4.2.9 on 2026-08-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_classroom_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
