# Generated by Django 6.0.7 on 2026-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_meeting_is_extended_meeting_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialchunk',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list, help_text='Float array representation for semantic search'),
        ),
    ]
