# Generated by Django 4.2.9 on 2026-02-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_mobilecamera_mobilecamerapermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobilecamerapermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mobilecamerapermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='mobilecamerapermission',
            name='mobile_camera',
        ),
        migrations.RemoveField(
            model_name='mobilecamerapermission',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='MobileCamera',
        ),
        migrations.DeleteModel(
            name='MobileCameraPermission',
        ),
    ]
