# Generated by Django 4.2.9 on 2026-03-18 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_add_left_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cameras', '0004_alter_mobilecamerapermission_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(choices=[('rtsp', 'RTSP Camera'), ('mobile', 'Mobile Camera')], default='rtsp', max_length=10)),
                ('camera_id', models.IntegerField()),
                ('camera_name', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], default='active', max_length=10)),
                ('capture_interval', models.IntegerField(default=30)),
                ('total_captures', models.IntegerField(default=0)),
                ('average_head_count', models.FloatField(default=0.0)),
                ('max_head_count', models.IntegerField(default=0)),
                ('min_head_count', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_count_sessions', to='meetings.classroom')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_count_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Head Count Session',
                'verbose_name_plural': 'Head Count Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HeadCountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(choices=[('rtsp', 'RTSP Camera'), ('mobile', 'Mobile Camera')], default='rtsp', max_length=10)),
                ('camera_id', models.IntegerField()),
                ('camera_name', models.CharField(max_length=100)),
                ('head_count', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='head_count_snapshots/')),
                ('notes', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_count_logs', to='meetings.classroom')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_count_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Head Count Log',
                'verbose_name_plural': 'Head Count Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['date', 'camera_type', 'camera_id'], name='cameras_hea_date_3c7af9_idx'), models.Index(fields=['classroom', 'date'], name='cameras_hea_classro_af7614_idx'), models.Index(fields=['hour', 'date'], name='cameras_hea_hour_a10332_idx')],
            },
        ),
    ]
