# Generated by Django 4.2.9 on 2026-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_headcountsession_headcountlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='rtsp_url',
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('rtsp', 'RTSP Camera'), ('ip_webcam', 'IP Webcam (Android)'), ('droidcam', 'DroidCam (iPhone)')], default='rtsp', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
