# Generated by Django 4.2.9 on 2026-05-12 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cameras', '0006_remove_camera_rtsp_url_camera_camera_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='recordings/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='recordings/thumbnails/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
