# Generated by Django 4.2.9 on 2026-05-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_camerarecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='livekit_room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camerarecording',
            name='recording_status',
            field=models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
