# Generated by Django 4.2.9 on 2026-05-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cameras', '0008_camera_livekit_room_camerarecording_recording_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='live_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_cameras', to=settings.AUTH_USER_MODEL),
        ),
    ]
