# Generated by Django 4.2.9 on 2026-05-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_camera_is_live_camera_live_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerarecording',
            name='recording_status',
            field=models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20),
        ),
    ]
