# Generated by Django 4.2.9 on 2026-05-15 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_alter_camerarecording_recording_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerarecording',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.camera'),
        ),
    ]
