# Generated by Django 4.2.9 on 2026-05-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_alter_camerarecording_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerarecording',
            name='is_chunked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecordingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('data', models.BinaryField()),
                ('duration', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='cameras.camerarecording')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('recording', 'sequence')},
            },
        ),
    ]
