# Generated by Django 4.2.9 on 2026-06-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0012_camerarecording_is_chunked_recordingchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerarecording',
            name='edit_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camerarecording',
            name='edit_start_time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
