# Generated by Django 4.2.9 on 2026-07-04 06:34

import cameras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0013_camerarecording_edit_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerarecording',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=cameras.models.get_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='camerarecording',
            name='video_file',
            field=models.FileField(upload_to=cameras.models.get_recording_upload_path),
        ),
    ]
