# Generated by Django 4.2.9 on 2026-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_alter_camerarecording_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerapermission',
            name='show_to_students',
            field=models.BooleanField(default=False),
        ),
    ]
