# Generated by Django 4.2.9 on 2026-07-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0015_camerapermission_show_to_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerarecording',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camerarecording',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
