# Generated by Django 6.0.7 on 2026-08-15 02:52

import cameras.models
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0016_camerarecording_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerarecording',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=cameras.models.get_thumbnail_upload_path, validators=[common.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='camerarecording',
            name='video_file',
            field=models.FileField(upload_to=cameras.models.get_recording_upload_path, validators=[common.validators.validate_video_file]),
        ),
    ]
