# Generated by Django 6.0.7 on 2026-09-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0017_alter_camerarecording_thumbnail_and_more'),
        ('meetings', '0016_meeting_is_extended_meeting_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerarecording',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='meetings.classroom'),
        ),
    ]
