# Generated by Django 6.0.7 on 2026-09-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0018_camerarecording_classroom'),
        ('meetings', '0016_meeting_is_extended_meeting_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerarecording',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='assigned_recordings', to='meetings.classroom'),
        ),
    ]
