# Generated by Django 4.2.9 on 2026-07-10 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import video_editing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('original_file', models.FileField(upload_to=video_editing.models.project_upload_path)),
                ('current_file', models.FileField(blank=True, null=True, upload_to=video_editing.models.project_upload_path)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('has_audio', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error')], default='ready', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('upload', 'Uploaded'), ('trim', 'Trimmed / Cut'), ('mute', 'Muted Audio'), ('unmute', 'Unmuted Audio'), ('volume', 'Adjusted Volume'), ('merge', 'Merged Clip'), ('text_overlay', 'Added Text Overlay'), ('speed', 'Changed Speed'), ('rotate', 'Rotated'), ('resize', 'Resized'), ('grayscale', 'Applied Grayscale'), ('fade', 'Applied Fade'), ('reset', 'Reset to Original')], max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='video_editing.videoproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
