# Generated by Django 4.2.9 on 2026-07-11 06:18

from django.db import migrations, models
import django.db.models.deletion
import video_editing.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='timeline_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to=video_editing.models.project_upload_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='video_editing.videoproject')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
