# Generated by Django 4.2.9 on 2026-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editing', '0003_editoperation_sync_db_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='clips_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='trim_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='trim_start',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='asset_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image')], default='video', max_length=10),
        ),
    ]
