# Generated by Django 6.0.7 on 2026-07-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editing', '0004_projectasset_title_videoproject_clips_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='proxy_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='proxy_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
