# Generated by Django 6.0.7 on 2026-08-21 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editing', '0005_videoproject_proxy_status_videoproject_proxy_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='editoperation',
            index=models.Index(fields=['project', 'active', '-created_at'], name='video_editi_project_d3d442_idx'),
        ),
        migrations.AddIndex(
            model_name='projectasset',
            index=models.Index(fields=['project', '-updated_at'], name='video_editi_project_ab576a_idx'),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['owner', '-updated_at'], name='video_editi_owner_i_e22cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['status'], name='video_editi_status_c24528_idx'),
        ),
    ]
