# Generated by Django 4.2.9 on 2026-09-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_editing', '0006_editoperation_video_editi_project_d3d442_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='clips_json',
        ),
    ]
