port: 7880
bind_addresses:
  - "0.0.0.0"
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false
  node_ip: "10.31.51.110"
  stun_servers: []

keys:
  edumi_livekit_key_2026: edumi_livekit_sec_32chars_key_2026_prod

room:
  empty_timeout: 300
  max_participants: 100

logging:
  level: info


