# Generated by Django 4.2.9 on 2026-07-02 09:39

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_quiz_quizsubmission_question_choice_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestionfile',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionfile',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentquestionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assignments.models.assignment_question_upload_path),
        ),
        migrations.AlterField(
            model_name='assignmentquestionfile',
            name='file_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assignments.models.assignment_submission_upload_path),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionfile',
            name='file_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', max_length=10),
        ),
    ]
