# Generated by Django 4.2.9 on 2026-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmentquestionfile_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the student opened the quiz', null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, help_text='Seconds taken to complete the quiz', null=True),
        ),
    ]
