# Generated by Django 6.0.7 on 2026-08-15 02:52

import assignments.models
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_quiz_timer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assignments.models.assignment_question_upload_path, validators=[common.validators.validate_assignment_file]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assignments.models.assignment_submission_upload_path, validators=[common.validators.validate_assignment_submission_file]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/questions/', validators=[common.validators.validate_image_file]),
        ),
    ]
