
from .utils import (
    get_video_stream,
    is_admin,
    can_view_camera,
    test_rtsp_paths,
    broadcast_live_status,
)
from .video_views import (
    like_recording,
    recording_analytics,
    stream_video, upload_video, camera_chunked_upload, recordings_folder, manage_recordings,
    toggle_recording_publish, watch_recording, stream_recording_chunk,
    recording_playlist, teacher_profile, delete_recording,
    update_recording_edit, apply_recording_trim, generate_recording_thumbnail,
    edit_recording,
)
from .camera_views import (
    admin_dashboard,
    add_camera,
    edit_camera,
    delete_camera,
    camera_feed,
    test_camera,
    test_feed_page,
    probe_camera,
)
from .streaming_views import (
    mobile_mic,
    teacher_camera_dashboard,
    teacher_control_room,
    update_zoom,
    start_streaming,
    stop_streaming,
    live_participants,
    student_lecture_list,
    watch_live,
    start_camera_recording,
    stop_camera_recording,
    publish_recording,
    camera_feed_proxy,
    clear_stream_cache,
)
from .permissions_views import (
    admin_content_manager,
    delete_recording_admin,
    delete_meeting_admin,
    grant_permission,
    revoke_permission,
    manage_permissions,
)
from .head_count_views import (
    head_count_dashboard,
    start_head_count,
    stop_head_count,
    head_count_logs,
    head_count_log_detail,
    head_count_session_history,
    head_count_api,
    head_count_report,
    export_head_count_csv,
)

__all__ = [
    # Utils
    'get_video_stream',
    'is_admin',
    'can_view_camera',
    'test_rtsp_paths',
    'broadcast_live_status',
    # Video
    'stream_video',
    'upload_video',
    'recordings_folder',
    'manage_recordings',
    'toggle_recording_publish',
    'watch_recording',
    'stream_recording_chunk',
    'recording_playlist',
    'teacher_profile',
    'delete_recording',
    'update_recording_edit',
    'apply_recording_trim',
    'generate_recording_thumbnail',
    'edit_recording',
    'like_recording',
    'recording_analytics',
    # Camera
    'admin_dashboard',
    'add_camera',
    'edit_camera',
    'delete_camera',
    'camera_feed',
    'test_camera',
    'test_feed_page',
    'probe_camera',
    # Streaming
    'mobile_mic',
    'teacher_camera_dashboard',
    'teacher_control_room',
    'update_zoom',
    'start_streaming',
    'stop_streaming',
    'live_participants',
    'student_lecture_list',
    'watch_live',
    'start_camera_recording',
    'stop_camera_recording',
    'publish_recording',
    'camera_feed_proxy',
    'clear_stream_cache',
    # Permissions
    'admin_content_manager',
    'delete_recording_admin',
    'delete_meeting_admin',
    'grant_permission',
    'revoke_permission',
    'manage_permissions',
    # Head Count
    'head_count_dashboard',
    'start_head_count',
    'stop_head_count',
    'head_count_logs',
    'head_count_log_detail',
    'head_count_session_history',
    'head_count_api',
    'head_count_report',
    'export_head_count_csv',
]
