# Generated by Django 4.2.9 on 2026-03-16 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0004_alter_meetingattendancelog_options_meetingsummary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embedding_encrypted', models.BinaryField()),
                ('embedding_checksum', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('face_quality_score', models.FloatField(default=0.0)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Face Profile',
                'verbose_name_plural': 'Student Face Profiles',
                'permissions': [('view_face_embedding', 'Can view face embedding (recognition service only)')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_recognition_enabled', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.55)),
                ('presence_duration_seconds', models.IntegerField(default=30)),
                ('late_threshold_minutes', models.IntegerField(default=10)),
                ('recognition_interval_seconds', models.IntegerField(default=15)),
                ('enforce_schedule', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='meetings.classroom')),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('match_success', 'Match Success'), ('match_failed', 'Match Failed'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('low_quality', 'Low Image Quality'), ('no_profile', 'No Face Profile Registered'), ('error', 'Processing Error')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_logs', to='meetings.meeting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'meeting'], name='attendance__student_c65e40_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='meetings.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('classroom', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('partial', 'Partial')], default='absent', max_length=10)),
                ('verification_method', models.CharField(choices=[('face_recognition', 'Face Recognition'), ('manual', 'Manual Override')], default='face_recognition', max_length=20)),
                ('face_match_confidence', models.FloatField(default=0.0)),
                ('face_verified_at', models.DateTimeField(blank=True, null=True)),
                ('marked_present_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='meetings.classroom')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendance_records', to='meetings.meeting')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'student'],
                'indexes': [models.Index(fields=['date', 'classroom'], name='attendance__date_c32126_idx'), models.Index(fields=['student', 'date'], name='attendance__student_588cfe_idx')],
                'unique_together': {('student', 'meeting')},
            },
        ),
    ]
