# Generated by Django 4.2.9 on 2026-03-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesettings',
            name='enforce_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
