# Generated by Django 4.2.9 on 2026-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_faceresetrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentengagementsnapshot',
            name='emotion',
            field=models.CharField(choices=[('focused', 'Focused'), ('happy', 'Happy'), ('surprised', 'Surprised'), ('tired', 'Tired/Sleeping'), ('confused', 'Confused'), ('distracted', 'Distracted'), ('absent', 'Not Visible'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
